### PR TITLE
Add ability to change connection method

### PR DESCRIPTION
**Pull request by eldario**
### Added

- Enabling command line control of the connection method

Fixes # (issue)
#33 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by tarampampam** [comment]
Maybe use [symfony/console](https://symfony.com/doc/current/console.html) for a working with command flags?

**Comment by eldario** [comment]
Another try with `InputInterface`, what do u think, @tarampampam?

**Comment by tarampampam** [comment]
Looks better, but not enough for production usage :(

**Comment by eldario** [comment]
I move in small steps so as not to do unnecessary work, @tarampampam

**Comment by tarampampam** [comment]
Already nade in #35, thank you!

**Pull request closed without merging**
